# Copyright 2013 Google Inc. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Datastore object to keep track of a single Pipeline run."""

import collections


from google.appengine.ext import ndb

from lib.crud import crud_model


class RunStat(crud_model.CrudNdbModel):
  """A RunStat to keep track of Pipelines."""
  parent_model_name = 'Pipeline'

  started = ndb.DateTimeProperty(auto_now_add=True)
  stopped = ndb.DateTimeProperty(auto_now=True)
  result_code = ndb.IntegerProperty()

  @staticmethod
  def GetHistory(this_pipeline):
    """Search for stats generated by this pipeline."""
    return RunStat.query(ancestor=this_pipeline)


class ResultCodes(object):
  """Types of pipeline run results. Currently with placeholders."""

  SUCCESS, FAILURE, TIME_OUT = range(3)

  messages = collections.OrderedDict(((SUCCESS, 'Pipeline run succeeded'),
                                      (FAILURE, 'Pipeline run failed'),
                                      (TIME_OUT, 'Pipeline run timed out')))

  @staticmethod
  def ToString(i):
    return ResultCodes.messages.get(i, 'Pipeline status unknown')
